INSERT INTO burgers (burger_name) VALUES ('Open Seasame Burger');
INSERT INTO burgers (burger_name) VALUES ('Kales From the Crypt Burger');
INSERT INTO burgers (burger_name) VALUES ('Knife to Meet You Burger Burger');
INSERT INTO burgers (burger_name) VALUES ('I Dont Bay Leaf in Magic Burger');
INSERT INTO burgers (burger_name) VALUES ('The Grand Brie Burger');
INSERT INTO burgers (burger_name) VALUES ('Top Bun Burger');
INSERT INTO burgers (burger_name) VALUES ('Winter Muensterland Burger');
INSERT INTO burgers (burger_name) VALUES ('National Pass-Thyme Burger');
INSERT INTO burgers (burger_name) VALUES ('Is This Your Chard Burger');
INSERT INTO burgers (burger_name) VALUES ('Bean Spirit Burger');