INSERT INTO burgers (burger_name, devoured) VALUES ('Open Seasame Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Kales From the Crypt Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Knife to Meet You Burger Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('I Dont Bay Leaf in Magic Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Grand Brie Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Top Bun Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Winter Muensterland Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('National Pass-Thyme Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Is This Your Chard Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Bean Spirit Burger', true);